![tower bridge](london.jpg)

London, or as the Romans called it "Londonium"! Home to [over 8.5 million residents](https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/bulletins/populationandhouseholdestimatesenglandandwales/census2021unroundeddata#population-and-household-estimates-england-and-wales-data) who speak over [300 languages](https://web.archive.org/web/20080924084621/http://www.cilt.org.uk/faqs/langspoken.htm). While the City of London is a little over one square mile (hence its nickname "The Square Mile"), Greater London has grown to encompass 32 boroughs spanning a total area of 606 square miles! 

![underground train leaving a platform](tube.jpg)

Given the city's roads were originally designed for horse and cart, this area and population growth has required the development of an efficient public transport system! Since the year 2000, this has been through the local government body called **Transport for London**, or *TfL*, which is managed by the London Mayor's office. Their remit covers the London Underground, Overground, Docklands Light Railway (DLR), buses, trams, river services (clipper and [Emirates Airline cable car](https://en.wikipedia.org/wiki/London_cable_car)), roads, and even taxis.

The Mayor of London's office make their data available to the public [here](https://data.london.gov.uk/dataset). In this project, you will work with a slightly modified version of a dataset containing information about public transport journey volume by transport type. 

The data has been loaded into a **Snowflake** database called `TFL` with a single table called `JOURNEYS`, including the following data:

## TFL.JOURNEYS

| Column | Definition | Data type |
|--------|------------|-----------|
| `MONTH`| Month in number format, e.g., `1` equals January | `INTEGER` |
| `YEAR` | Year | `INTEGER` |
| `DAYS` | Number of days in the given month | `INTEGER` |
| `REPORT_DATE` | Date that the data was reported | `DATE` |
| `JOURNEY_TYPE` | Method of transport used | `VARCHAR` |
| `JOURNEYS_MILLIONS` | Millions of journeys, measured in decimals | `FLOAT` |

Note that *in Snowflake all databases, tables, and columns are **upper case*** by default.

You will execute SQL queries to answer three questions, as listed in the instructions.

## Write three SQL queries to answer the following questions:

1 - What are the most popular transport types, measured by the total number of journeys? The output should contain two columns, 1) JOURNEY_TYPE and 2) TOTAL_JOURNEYS_MILLIONS, and be sorted by the second column in descending order. Save the query as most_popular_transport_types.

2 - Which five months and years were the most popular for the Emirates Airline? Return an output containing MONTH, YEAR, and JOURNEYS_MILLIONS, with the latter rounded to two decimal places and aliased as ROUNDED_JOURNEYS_MILLIONS. Exclude null values and save the result as emirates_airline_popularity.

3 - Find the five years with the lowest volume of Underground & DLR journeys, saving as least_popular_years_tube. The results should contain the columns YEAR, JOURNEY_TYPE, and TOTAL_JOURNEYS_MILLIONS.

Three SQL cells have been created for you in the workbook. To access the Snowflake database, you will need to select data using the syntax FROM TFL.JOURNEYS (ensure you use upper-case).

Note: Please also ensure that you do not change the names of the DataFrames that the three query results will be saved as - creating new cells in the workbook will rename the DataFrame (see image below). Make sure that your final solutions use the names provided: most_popular_transport_types, emirates_airline_popularity, and least_popular_years_tube.

In [ ]:
-- most_popular_transport_types
SELECT 
	JOURNEY_TYPE,
	ROUND(SUM(JOURNEYS_MILLIONS),2) AS TOTAL_JOURNEYS_MILLIONS
FROM
	TFL.JOURNEYS
GROUP BY JOURNEY_TYPE
ORDER BY TOTAL_JOURNEYS_MILLIONS DESC;

In [ ]:
-- emirates_airline_popularity

SELECT 
	MONTH,
	YEAR,
	ROUND(SUM(JOURNEYS_MILLIONS),2) AS ROUNDED_JOURNEYS_MILLIONS
FROM
	TFL.JOURNEYS
WHERE JOURNEYS_MILLIONS IS NOT NULL AND JOURNEY_TYPE = 'Emirates Airline'
GROUP BY MONTH,YEAR
ORDER BY ROUNDED_JOURNEYS_MILLIONS DESC
LIMIT 5;

   MONTH  YEAR  ROUNDED_JOURNEYS_MILLIONS
0      5  2012                       0.53
1      6  2012                       0.38
2      4  2012                       0.24
3      5  2013                       0.19
4      5  2015                       0.19

In [ ]:
-- least_popular_years_tube
SELECT 
	YEAR,
	JOURNEY_TYPE,
	ROUND(SUM(JOURNEYS_MILLIONS),2) AS TOTAL_JOURNEYS_MILLIONS
FROM
	TFL.JOURNEYS
WHERE JOURNEYS_MILLIONS IS NOT NULL AND JOURNEY_TYPE = 'Underground & DLR'
GROUP BY YEAR, JOURNEY_TYPE
ORDER BY TOTAL_JOURNEYS_MILLIONS
LIMIT 5;

   YEAR       JOURNEY_TYPE  TOTAL_JOURNEYS_MILLIONS
0  2020  Underground & DLR                   310.18
1  2021  Underground & DLR                   748.45
2  2022  Underground & DLR                  1064.86
3  2010  Underground & DLR                  1096.15
4  2011  Underground & DLR                  1156.65